### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by kodbakelse** [UltiNaruto/MP1_Trilogy_Rando_Generator#1]
When I try to generate a template for ISO for Prime 1 Randomizer I get an error saying
Could not find a part of the path '.\temp\wii\DATA\files\rs5mp1_p.dol'.

Any way to fix this?

**Comment by UltiNaruto** [comment]
did you keep the ISO extracted? both .\tmp\wii and gc_template.iso must be kept to prevent extra delay from reextracting the iso

**Comment by kodbakelse** [comment]
.\tmp\wii is there and I can't find any file named gc_template.iso. There's nothing in the .\tmp\wii folder though.

**Comment by UltiNaruto** [comment]
have you generated the gc_template.iso file?

**Comment by kodbakelse** [comment]
I assume that's what you get when you click "Generate a template ISO for Prime 1 Randomizer" and select a Metroid Prime Trilogy ISO, however doing that is when I get the error message. It never generates any files.

**Comment by UltiNaruto** [comment]
what kind of ISO are you using for the input file?
I mean (ciso, nkit, iso)

**Comment by kodbakelse** [comment]
The file is called Metroid Prime Trilogy (USA).nkit.iso.

**Comment by UltiNaruto** [comment]
ah nkit is only supported since last version

**Comment by kodbakelse** [comment]
Poop. So I gotta get another trilogy ISO entirely then?

**Comment by UltiNaruto** [comment]
No just use the latest version

**Comment by kodbakelse** [comment]
Oh I thought you meant nkit isn't supported since the last version lol.
I am using 1.7 though, isn't that the latest version?

**Comment by UltiNaruto** [comment]
it is

**Comment by kodbakelse** [comment]
So then what could be the problem if I'm using the latest version?

**Comment by UltiNaruto** [comment]
try to delete back the tmp\wii folder and regenerate the template iso again

**Comment by kodbakelse** [comment]
Oh, that fixed it! I guess I just needed to delete the tmp\wii folder and let it create a new one.
Thanks for the help, I appreciate the quick response!

**Comment by UltiNaruto** [comment]
No problem. Have fun.
